### PR TITLE
KEP 90: Lifecycle Toolkit - Runtime Adaptions

### PR DESCRIPTION
**Pull request by thschue**
Signed-off-by: Thomas Schuetz <thomas.schuetz@dynatrace.com>

### CODE REVIEW

**Comment by agardnerIT** [comment]
Love this idea and support. 1 suggestion: For the returned JSON, can we make this [cloudevents ](https://cloudevents.io) compliant?

Can this event also either be a standard cdevent (it doesn't quite fit but perhaps a [testcase-finished](https://github.com/cdevents/spec/blob/v0.1.1/continuous-integration-pipeline-events.md#testcase-finished) OR if there isn't [a suitable event type](https://cdevents.dev/docs/) - we propose a new set of events to cdevents.

**Comment by bradmccoydev** [comment]
@agardnerIT Test event types are being developed for cdEvents and there is a discussion on this at the moment, Ole from Kubeshop is leading this I will send a link to the draft when i find it. some context might also be in here: https://hackmd.io/2FRGlw9fTMmKN1OQUVvguA

**Comment by thschue** [comment]
One option to get more insights into the runtime might be a running sidecar with an API exposed to the Controller (and secured by network policies), which allows the lifecycle controller to fetch the status, gather the results, or stop the job.

**Review by thisthat — APPROVED** [review]

**Review by AnaMMedina21 — DISMISSED** [review]
Approved! bash and python would definitely be great additions for

> One option to get more insights into the runtime might be a running sidecar with an API exposed to the Controller (and secured by network policies), which allows the lifecycle controller to fetch the status, gather the results, or stop the job.

@thschue; Are you thinking about the sidecar helping Keptn infer the runtime specs without user input? I do think that fetching status/results would be a nice to have

**Review by bradmccoydev — DISMISSED** [review]

**Review by thisthat — APPROVED** [review]

**Review by bradmccoydev — APPROVED** [review]

**Pull request merged**
